# Neural Nets practice

<a href="https://colab.research.google.com/github/HassanAlgoz/dl/blob/main/modules/M2/03-nn-modules/03-nn-modules.ipynb" target="_blank">
  <img src="https://raw.githubusercontent.com/HassanAlgoz/dl/main/assets/Open%20in%20Colab-F9AB00.svg" alt="Open in Colab" height="50"/>
</a>


In [1]:
# --- Setup: Clone repo & cd into correct folder (for lab setup convenience) ---
import os
import subprocess

repo_url = "https://github.com/HassanAlgoz/dl.git"
lab_folder = "dl/modules/M2/03-nn-modules"

# Only clone if the folder doesn't exist
if not os.path.exists(lab_folder):
    subprocess.run(["git", "clone", repo_url])

# Change working directory to the lab folder
os.chdir(lab_folder)


We're giving you some code to help you get started. The exercises will have you modify the following code to build up your PyTorch knowledge.

In [ ]:
%pip install -qqq torch


In [2]:
# imports
import torch
import torch.nn as nn
import torch.nn.functional as F


In [ ]:
# model = nn.Sequential(
#     nn.Linear(1, 3)
#     nn.ReLU(),
#     nn.Linear(3, 1)
# )

In [3]:
# Building a simple NN
class SimpleDNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleDNN, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

In [4]:
# Initialize the model
input_size = 2
hidden_size = 4
output_size = 1
model = SimpleDNN(input_size, hidden_size, output_size)
print(model)

SimpleDNN(
  (fc1): Linear(in_features=2, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=1, bias=True)
)


---

## Exercise 1:

Create a Network Modify the above network to include three hidden layers with ReLU activations.

Exercise 1: Modify Model Structure

1. Add a new hidden layer with 6 neurons to the SimpleDNN class.
2. Use ReLU activation for the new layer.
3. Print the updated model structure.

In [5]:
# Solution for Exercise 1
class UpdatedDNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(UpdatedDNN, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.fc3 = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# Initialize the updated model
model = UpdatedDNN(input_size=2, hidden_size=6, output_size=1)
print(model)

UpdatedDNN(
  (fc1): Linear(in_features=2, out_features=6, bias=True)
  (fc2): Linear(in_features=6, out_features=6, bias=True)
  (fc3): Linear(in_features=6, out_features=1, bias=True)
)


---

We're going to create the following model for the next exercise, `MultiLayerDNN`

In [6]:
class MultiLayerDNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(MultiLayerDNN, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.fc3 = nn.Linear(hidden_size, hidden_size)
        self.fc4 = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = self.fc4(x)
        return x

# Initialize the new model
model = MultiLayerDNN(input_size, hidden_size, output_size)
print(model)

MultiLayerDNN(
  (fc1): Linear(in_features=2, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=4, bias=True)
  (fc3): Linear(in_features=4, out_features=4, bias=True)
  (fc4): Linear(in_features=4, out_features=1, bias=True)
)


---

## Exercise 2:

Forward Pass with New Input

1. Generate a new input tensor with shape (5, 2).
2. Perform a forward pass using the 3 MultiLayerDNN class.
3. Print the resulting outputs.

In [8]:
model

MultiLayerDNN(
  (fc1): Linear(in_features=2, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=4, bias=True)
  (fc3): Linear(in_features=4, out_features=4, bias=True)
  (fc4): Linear(in_features=4, out_features=1, bias=True)
)

In [12]:
new_inputs = torch.randn(3, 2)
new_inputs

tensor([[ 0.0780, -0.2902],
        [ 0.9681, -1.5698],
        [ 1.3181, -0.6134]])

In [13]:
outputs = model(new_inputs)
outputs

tensor([[-0.6519],
        [-0.6511],
        [-0.6934]], grad_fn=<AddmmBackward0>)

In [7]:
# Solution for Exercise 2
new_inputs = torch.randn(5, 2)
outputs = model(new_inputs)
print("New Input Tensor:")
print(new_inputs)
print("Outputs:")
print(outputs)

New Input Tensor:
tensor([[ 1.3522,  0.0112],
        [ 0.4402, -0.8345],
        [ 0.6487,  1.8623],
        [-0.8002,  2.1597],
        [ 1.2837, -1.2000]])
Outputs:
tensor([[-0.7048],
        [-0.6515],
        [-0.6941],
        [-0.6550],
        [-0.6647]], grad_fn=<AddmmBackward0>)
